services:
  app:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      NEXT_PUBLIC_IMAGES_URL: ${NEXT_PUBLIC_IMAGES_URL}
      BITPAY_API: ${BITPAY_API}
      BITPAY_REDIRECT: ${BITPAY_REDIRECT}
      BITPAY_PORTAL_URL: ${BITPAY_PORTAL_URL}
